# Generated by Django 3.1.2 on 2020-10-12 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20201012_0824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocks',
            name='today_price',
        ),
    ]
