# Generated by Django 3.1.2 on 2020-10-14 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_remove_stocks_today_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='symbol',
            field=models.CharField(max_length=200),
        ),
    ]
