# Generated by Django 3.1.3 on 2020-11-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20201014_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks',
            name='coin',
            field=models.BooleanField(default=False),
        ),
    ]
